### ISSUE TITLE
crash: run stable-diffusion sdxl when use flash attn

### ISSUE THREAD

**Issue by ruitard** [huggingface/candle#1156]
```shell
target/release/examples/stable-diffusion --prompt "An astronaut riding a green horse" --sd-version xl --use-f16 --use-flash-attn
```
it crashed.
```text
Running with prompt "An astronaut riding a green horse".
Building the Clip transformer.
Running with prompt "An astronaut riding a green horse".
Building the Clip transformer.
Tensor[dims 2, 77, 2048; f16, cuda:6]
Building the autoencoder.
Building the unet.
thread 'main' panicked at /root/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/cudarc-0.9.14/src/driver/safe/core.rs:208:76:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_LAUNCH_FAILED, "unspecified launch failure")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /root/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/cudarc-0.9.14/src/driver/safe/core.rs:208:76:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_LAUNCH_FAILED, "unspecified launch failure")
stack backtrace:
   0:     0x5593af7e325c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5593af7e325c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5593af7e325c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5593af7e325c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
```

**Comment by ruitard** [comment]
then I run
```shell
compute-sanitizer --tool memcheck target/debug/examples/stable-diffusion --prompt "An astronaut riding a green horse" --sd-version xl --use-f16 --use-flash-attn
```
[log.txt](https://github.com/huggingface/candle/files/13065892/log.txt)

**Comment by LaurentMazare** [comment]
What GPU are you using this one? Fwiw flash-attn-v2 is only supporting Ampere, Ada, or Hopper GPUs (e.g., A100, RTX 3090, RTX 4090, H100).

**Comment by ruitard** [comment]
> What GPU are you using this one? Fwiw flash-attn-v2 is only supporting Ampere, Ada, or Hopper GPUs (e.g., A100, RTX 3090, RTX 4090, H100).

is V100
