### ISSUE TITLE
ONNX: unsupported op_type If for op NodeProto

### ISSUE THREAD

**Issue by garyhai** [huggingface/candle#1329]
Failed to load voice detection model [silero_vad.onnx](https://github.com/snakers4/silero-vad/blob/master/files/silero_vad.onnx) with candle-onnx.

```
thread 'main' panicked at audio/examples/segment.rs:33:44:
failed to segment audio: unsupported op_type If for op NodeProto { input: ["onnx::Cast_125"], output: ["output", "hn", "cn"], name: "If_25", op_type: "If", domain: "", attribute: [AttributeProto { name: "else_branch", ref_attr_name: "", doc_string: "", r#type: Graph, f: 0.0, i: 0, s: [], t: None, g: Some(GraphProto { node: [NodeProto { input: ["input"], output: ["622"], name: "Shape_502", op_type: "Shape", domain: "", attribute: [AttributeProto { name: "start", ref_attr_name: "", doc_string: "", r#type: Int, f: 0.0, i: 0, s: [], t: None, g: None, sparse_tensor: None, tp: None, floats: [], ints: [], strings: [], tensors: [], graphs: [], sparse_tensors: [], type_protos: [] }], doc_string: "" }, NodeProto { input: ["622", "623"], output: ["num_samples.3"], name: "Gather_504", op_type: "Gather", domain: "", attribute: [AttributeProto { name: "axis", ref_attr_name: "", doc_string: "", r#type: Int, f: 0.0, i: 0, s: [], t: None, g: None, sparse_tensor: None, tp: None, floats: [], ints: [], strings: [], tensors: [], graphs: [], sparse_tensors: [], type_protos: [] }], doc_string: "" }, NodeProto { input: ["num_samples.3", "629"], output: ["630"], name: "Unsqueeze_510", op_type: "Unsqueeze", domain: "", attribute: [], doc_string: "" },
...
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/backtrace.rs:331:13
   3: std::backtrace::Backtrace::capture
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/backtrace.rs:297:9
   4: candle_core::error::Error::bt
             at /Users/gary/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.3.1/src/error.rs:227:25
   5: candle_onnx::eval::simple_eval
             at /Users/gary/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-onnx-0.3.1/src/eval.rs:744:24
   6: ican_audio::vad::VadSession::feed_chunk
             at ./audio/src/vad.rs:269:22
   7: ican_audio::vad::VadSession::segment
             at ./audio/src/vad.rs:454:7
   8: ican_audio::vad::VadSession::segment_audio
             at ./audio/src/vad.rs:484:5
   9: segment::main
             at ./audio/examples/segment.rs:33:18

...
```

**Comment by garyhai** [comment]
**Issue Closed: Problem Resolved**

After thorough testing, we have verified that the issue regarding the unsupported `op_type: If` for `NodeProto` in ONNX has been resolved. The behavior is now functioning as expected, and no further issues were encountered in the latest implementation.

For further context, you can refer to my project [garyhai/tinker-vad](https://github.com/garyhai/tinker-vad), which explores similar use cases of ONNX. This project showcases voice activity detection (VAD) models with ONNX integration and provides additional insights into model compatibility and optimization.

Thank you to the team and contributors for addressing this matter. If anyone experiences similar issues or has additional feedback, feel free to open a new issue.
