### ISSUE TITLE
max_pool2d crashes when dimensions smaller than max_pool kernel size

### ISSUE THREAD

**Issue by rockerBOO** [huggingface/candle#1445]
I'm doing a UNet (maybe poorly) and using image latents from the VAE. In the convolution it gets down to (64,1,1) and batch size of 1. The UNet says to get a max_pool_2d of (2, 2) with a 2 stride. This is causing the network to crash when it subtracts the height (1) or width (1) by the pool size (2). 

Example code:

```rust
use candle_core::{Device, Result, Tensor};

fn main() -> Result<()> {
    let xs = Tensor::arange::<f32>(0., 64., &Device::Cpu)?.reshape((1, 64, 1, 1))?;

    let xs = xs.max_pool2d(2)?;
    println!("{}", xs);

    Ok(())
}
```
```
RUST_BACKTRACE=1  cargo run --bin max_pool
warning: unused manifest key: default_run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/max_pool`
thread 'main' panicked at /home/rockerboo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.3.1/src/tensor.rs:1066:21:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   3: candle_core::tensor::Tensor::max_pool2d_with_stride
             at /home/rockerboo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.3.1/src/tensor.rs:1066:21
   4: candle_core::tensor::Tensor::max_pool2d
             at /home/rockerboo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.3.1/src/tensor.rs:1052:9
   5: max_pool::main
             at ./src/bin/max_pool.rs:6:14
   6: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

http://github.com/huggingface/candle/blob/77252ffb82e328322951becda5fef1e261daa9a9/candle-core/src/tensor.rs#L1070-L1071

Now I think I am maybe doing something wrong for this result to happen but I'm still learning. I believe this works on the Pytorch version though (I trained it on Pytorch with the same latent at least). 

I would expect the code would just return the value if it is just the value if it's the only value in that dimension. Maybe that's not how it's suppose to work though...

Thank you!

**Comment by kuzemchik** [comment]
I would say pytorch has same behavior. With slightly better explanation though.

```
>>> t = torch.arange(0.0,64.0).reshape((1,64,1,1))
>>> pooled = nn.MaxPool2d(2)
>>> pooled.forward(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nogod/p3/lib/python3.11/site-packages/torch/nn/modules/pooling.py", line 166, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nogod/p3/lib/python3.11/site-packages/torch/_jit_internal.py", line 488, in fn
    return if_false(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nogod/p3/lib/python3.11/site-packages/torch/nn/functional.py", line 791, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given input size: (64x1x1). Calculated output size: (64x0x0). Output size is too small
```

**Comment by rockerBOO** [comment]
Thank you @kuzemchik ! I should've had confirmed it in PyTorch. 

Please close if it is not a bug to have it hard crash.

**Comment by LaurentMazare** [comment]
Thanks for pointing this out, the hard crash is indeed a bit unfortunate. I've tweaked that to be a proper error in #1473 so that it can be caught easily by the caller.

**Comment by LaurentMazare** [comment]
Closing out as hopefully fixed but feel free to reopen if it's still an issue to you.
