### ISSUE TITLE
CUDA_ERROR_UNKNOWN running examples

### ISSUE THREAD

**Issue by dr3s** [huggingface/candle#1480]
Running any of the examples using cuda gives me an unknown error.  

System:
Lambda vector (2x4090)
Ubuntu 22

```
candle/candle-examples on  main [!] is 📦 v0.3.2 via 🦀 v1.73.0 
❯ nvidia-smi 
Mon Dec 25 14:22:05 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:41:00.0  On |                  Off |
|  0%   31C    P8              35W / 480W |    865MiB / 24564MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  | 00000000:61:00.0 Off |                  Off |
|  0%   27C    P8              15W / 480W |    687MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

```

Pytorch looks ok
```
❯ python3 -c "import torch; print(torch.cuda.device_count())"
2

```

Error:
```
candle/candle-examples on  main [!] is 📦 v0.3.2 via 🦀 v1.73.0 
❯ cargo run --features cuda --example whisper --release 
    Finished release [optimized] target(s) in 0.12s
     Running `/home/dres/src/gh/candle/target/release/examples/whisper`
thread 'main' panicked at /home/dres/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.9.15/src/driver/safe/core.rs:51:24:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_UNKNOWN, "unknown error")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: cudarc::driver::safe::core::CudaDevice::new
   4: <candle_core::cuda_backend::CudaDevice as candle_core::backend::BackendDevice>::new
   5: candle_core::device::Device::new_cuda
   6: candle_examples::device
   7: whisper::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by LaurentMazare** [comment]
It's a bit to hard to diagnose what is going on as the error message is not very informative.
I would suggest trying to run the examples/tests from the [cudarc crate](https://github.com/coreylowman/cudarc) (which candle uses behind the hood), if they don't work this would indicate more of a general cuda issue rather than a candle specific one.

**Comment by dr3s** [comment]
erm disregard.  This was due to some cuda init issue.  A reboot fixed it.

```
❯ cargo run --features cuda --example whisper --release 
   Compiling candle-transformers v0.3.2 (/home/dres/src/gh/candle/candle-transformers)
   Compiling candle-examples v0.3.2 (/home/dres/src/gh/candle/candle-examples)
    Finished release [optimized] target(s) in 9.45s
     Running `target/release/examples/whisper`
No audio file submitted: Downloading https://huggingface.co/datasets/Narsil/candle_demo/blob/main/samples_jfk.wav
loaded wav data: Header { audio_format: 1, channel_count: 1, sampling_rate: 16000, bytes_per_second: 32000, bytes_per_sample: 2, bits_per_sample: 16 }
pcm data loaded 176000
loaded mel: [1, 80, 3000]
0.0s -- 30.0s:  And so my fellow Americans ask not what your country can do for you ask what you can do for your country

```
