### ISSUE TITLE
question: what GPU can run the mixtral example?

### ISSUE THREAD

**Issue by zwpaper** [huggingface/candle#1733]
I found the mixtral example in this repo, and try to run it on A100 80GB, but the default Mixtral-8x7B-v0.1 runs out of memory.

I was curious what GPU can run it in one card?

**Comment by okpatil4u** [comment]
I was able to run it on M1 Mac Max (64GB RAM) laptop. 80GB should be more
than sufficient to run it.

Did you run quantized version ?

**Comment by groovybits** [comment]
Ah this runs my 192 gig M2 Ultra out of ram :/ It seems crazy loading 100+ till it breaks for me. How do we use the quantized version exactly? I didn't realize it was running the full model but starting suspecting that. This sounds hopeful, was worried it was broken which I really love Mixtral :)

**Comment by okpatil4u** [comment]
It’s in the quantized folder inside examples. Just choose mixtral as
default model in the command line and it should work.

**Comment by LaurentMazare** [comment]
Could you try running this with `RUST_BACKTRACE=1`, this would help pinpointing at where the issues actually is.

**Comment by cloneable** [comment]
I tried unquantized Mixtral example on my M3 Max 128G, but also ran out of memory. MLX's Mixtral example works fine. Maybe `candle` allocates buffers twice (mmap + gpu) because Metal's `new_buffer_with_bytes_no_copy` is not used?

**Comment by kurtbuilds** [comment]
I'm also encountering this. Running the Q4_K_M version of this model: https://huggingface.co/TheBloke/dolphin-2.7-mixtral-8x7b-GGUF/blob/main/dolphin-2.7-mixtral-8x7b.Q4_K_M.gguf

Full stack trace:

thread 'main' panicked at inference_demo/src/main.rs:178:11:
called `Result::unwrap()` on an `Err` value: device mismatch in matmul, lhs: Metal { gpu_id: 4294969767 }, rhs: Cpu
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/backtrace.rs:331:13
   3: candle_core::error::Error::bt
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/error.rs:227:25
   4: candle_core::storage::Storage::same_device
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/storage.rs:49:17
   5: candle_core::storage::Storage::matmul
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/storage.rs:655:9
   6: candle_core::tensor::Tensor::matmul
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/tensor.rs:1169:23
   7: <candle_core::quantized::QMatMul as candle_core::Module>::forward
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/quantized/mod.rs:487:17
   8: candle_transformers::models::quantized_llama::QMatMul::forward
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-transformers-0.4.1/src/models/quantized_llama.rs:46:9
   9: <candle_transformers::models::quantized_llama::MlpOrMoe as candle_core::Module>::forward
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-transformers-0.4.1/src/models/quantized_llama.rs:86:37
  10: candle_transformers::models::quantized_llama::ModelWeights::forward
             at /Users/kurt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-transformers-0.4.1/src/models/quantized_llama.rs:510:21
  11: inference_demo::TextGeneration::run
             at ./src/main.rs:55:26
  12: inference_demo::main
             at ./src/main.rs:156:5

**Comment by LaurentMazare** [comment]
That's odd, I just ran the model you mentioned on cuda without any issue (and cuda / metal should have similar behavior when it comes to such errors).
Is it possible that your code in `inference_demo` is not moving the input tensors to the metal device and keeps them on cpu?

**Comment by kurtbuilds** [comment]
How would I check that?

**Comment by LaurentMazare** [comment]
There is no implicit device in candle so you explicitely set the device each time you create a tensor or the device is inferred from the argument in the case of operations on tensors. You would want to check that the tensor inputs are appropriately sent on your device as is done [here](https://github.com/huggingface/candle/blob/66f0a4eeea02f069838903a18dd6402821e43271/candle-examples/examples/quantized/main.rs#L529) for example. You would also want to check that you're loading the model on the same device. My guess is that somewhere in your code you may have some hardcoded `Device::Cpu`.
You can also print the device of your tensor so that it's easier to narrow done where this is coming from.

**Comment by somethingelseentirely** [comment]
The hardcoded `Device::Cpu` was actually in the quantized `matmul` implementation of `candle-core v4.1`, so at least that one is solved 😄
