### ISSUE TITLE
examples/marian-mt/convert_slow_tokenizer.py not working

### ISSUE THREAD

**Issue by def-roth** [huggingface/candle#2409]
Reproduce:

Run convert_slow_tokenizer.py as told  https://github.com/huggingface/candle/issues/1177#issuecomment-1786468158

Error

```
python converter.py 
['/home/device1/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-fr-en/snapshots/b4a9a384c2ec68a224bbd2ee3fd5df0c71ca5b1b/source.spm', '/home/device1/.cache/huggingface/hub/models--Helsinki-NLP--opus-mt-fr-en/snapshots/b4a9a384c2ec68a224bbd2ee3fd5df0c71ca5b1b/target.spm']
MarianTokenizer(name_or_path='Helsinki-NLP/opus-mt-fr-en', vocab_size=59514, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
        0: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        1: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        59513: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
Ignored missing piece <s>
Ignored missing piece |
Ignored missing piece ▁|
Traceback (most recent call last):
  File "home/device1/PycharmProjects/rust_utils/converter.py", line 6, in <module>
    fast_tokenizer = MarianConverter(tokenizer, index=0).converted()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "home/device1/PycharmProjects/rust_utils/convert_slow_tokenizer.py", line 540, in converted
    pre_tokenizer = self.pre_tokenizer(replacement, add_prefix_space)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "home/device1/PycharmProjects/rust_utils/convert_slow_tokenizer.py", line 522, in pre_tokenizer
    return pre_tokenizers.Metaspace(replacement=replacement, add_prefix_space=add_prefix_space)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Metaspace.__new__() got an unexpected keyword argument 'add_prefix_space'


```

**Comment by LaurentMazare** [comment]
Thanks for reporting this, I think this was broken in version of tokenizers >= 0.19. I'm pushing #2426 so that this version works fine.

**Comment by LaurentMazare** [comment]
Closing as hopefully fixed but feel free to re-open if needed.
