### ISSUE TITLE
assertion failed: !ptr.is_null() with Stable Diffusion img2img on metal 

### ISSUE THREAD

**Issue by wooden-worm** [huggingface/candle#2417]
Command:
```
cargo run --example stable-diffusion --features=metal -- --prompt "a cosmonaut on a horse (hd, realistic, high-def)" --img2img [path_to_img]
```

Stacktrace
```
thread 'main' panicked at /Users/worm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foreign-types-shared-0.3.1/src/lib.rs:72:9:
assertion failed: !ptr.is_null()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:146:5
   3: foreign_types_shared::ForeignTypeRef::from_ptr
             at /Users/worm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foreign-types-shared-0.3.1/src/lib.rs:72:9
   4: <metal::buffer::Buffer as core::ops::deref::Deref>::deref
             at /Users/worm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/metal-0.27.0/src/lib.rs:169:9
   5: <&metal::buffer::Buffer as candle_metal_kernels::utils::EncoderParam>::set_param
             at ./candle-metal-kernels/src/utils.rs:125:43
   6: candle_metal_kernels::utils::set_param
             at ./candle-metal-kernels/src/utils.rs:69:5
   7: candle_metal_kernels::call_im2col_strided
             at ./candle-metal-kernels/src/utils.rs:158:13
   8: <candle_core::metal_backend::MetalStorage as candle_core::backend::BackendStorage>::conv2d
             at ./candle-core/src/metal_backend/mod.rs:962:9
   9: candle_core::storage::Storage::conv2d
             at ./candle-core/src/storage.rs:443:25
  10: candle_core::conv::<impl candle_core::tensor::Tensor>::conv2d_single_group
             at ./candle-core/src/conv.rs:258:13
  11: candle_core::conv::<impl candle_core::tensor::Tensor>::conv2d
             at ./candle-core/src/conv.rs:301:13
  12: <candle_nn::conv::Conv2d as candle_core::Module>::forward
             at ./candle-nn/src/conv.rs:214:17
  13: <candle_transformers::models::with_tracing::Conv2d as candle_core::Module>::forward
             at ./candle-transformers/src/models/with_tracing.rs:85:9
  14: candle_transformers::models::stable_diffusion::resnet::ResnetBlock2D::forward
             at ./candle-transformers/src/models/stable_diffusion/resnet.rs:124:18
  15: <candle_transformers::models::stable_diffusion::unet_2d_blocks::DownEncoderBlock2D as candle_core::Module>::forward
             at ./candle-transformers/src/models/stable_diffusion/unet_2d_blocks.rs:180:18
  16: candle_core::tensor::Tensor::apply
             at ./candle-core/src/tensor.rs:2285:9
  17: candle_transformers::models::stable_diffusion::vae::Encoder::forward
             at ./candle-transformers/src/models/stable_diffusion/vae.rs:138:18
  18: candle_transformers::models::stable_diffusion::vae::AutoEncoderKL::encode
             at ./candle-transformers/src/models/stable_diffusion/vae.rs:375:18
  19: stable_diffusion::run
             at ./candle-examples/examples/stable-diffusion/main.rs:521:18
  20: stable_diffusion::main
             at ./candle-examples/examples/stable-diffusion/main.rs:630:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ealmloff** [comment]
I get the same panic when trying to create a `Tensor` from an empty iterator on metal which might be easier to debug/reproduce:
```rust
// [package]
// name = "candle-panic"
// version = "0.1.0"
// edition = "2021"

// [dependencies]
// candle-core = { version = "0.8.2", features = ["metal"] }
// safetensors = "0.4.0"

use candle_core::{Device, Tensor};

fn main() {
    let device = Device::new_metal(0).unwrap();
    let tensors = [("testing", Tensor::from_iter([] as [u32; 0], &device).unwrap())];
    safetensors::serialize(tensors, &None).unwrap();
}
```

<details>
<summary>full backtrack</summary>

```
thread 'main' panicked at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foreign-types-shared-0.3.1/src/lib.rs:72:9:
assertion failed: !ptr.is_null()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:76:14
   2: core::panicking::panic
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:148:5
   3: foreign_types_shared::ForeignTypeRef::from_ptr
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foreign-types-shared-0.3.1/src/lib.rs:72:9
   4: <metal::buffer::Buffer as core::ops::deref::Deref>::deref
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/metal-0.27.0/src/lib.rs:169:9
   5: candle_core::metal_backend::MetalStorage::to_cpu
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.8.2/src/metal_backend/mod.rs:1866:35
   6: <candle_core::metal_backend::MetalStorage as candle_core::backend::BackendStorage>::to_cpu_storage
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.8.2/src/metal_backend/mod.rs:100:46
   7: candle_core::tensor::Tensor::to_vec1
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.8.2/src/tensor.rs:1626:58
   8: candle_core::safetensors::convert_back
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.8.2/src/safetensors.rs:236:47
   9: candle_core::safetensors::<impl safetensors::tensor::View for candle_core::tensor::Tensor>::data
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.8.2/src/safetensors.rs:60:20
  10: safetensors::tensor::serialize
             at /Users/evanalmloff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/safetensors-0.4.5/src/tensor.rs:235:23
  11: candle_segfault::main
             at ./src/main.rs:16:5
  12: core::ops::function::FnOnce::call_once
             at /Users/evanalmloff/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>
