### ISSUE TITLE
llama convert_checkpont error

### ISSUE THREAD

**Issue by rockyzhengwu** [huggingface/candle#391]
https://github.com/huggingface/candle/blob/385f0d261c9199b83373fc10b7b52a1fef67a9d0/candle-examples/examples/llama/convert_checkpoint.py#L173

```
Traceback (most recent call last):                                                                                                                                                  20:17:17
  File "/home/zhengwu/workspace/Github/candle/candle-examples/examples/llama/convert_checkpoint.py", line 199, in <module>
    main()
  File "/home/zhengwu/workspace/Github/candle/candle-examples/examples/llama/convert_checkpoint.py", line 191, in main
    write_model(
  File "/home/zhengwu/workspace/Github/candle/candle-examples/examples/llama/convert_checkpoint.py", line 173, in write_model
    all_dicts = {k: v.numpy() for k, v in all_dicts.items()}
  File "/home/zhengwu/workspace/Github/candle/candle-examples/examples/llama/convert_checkpoint.py", line 173, in <dictcomp>
    all_dicts = {k: v.numpy() for k, v in all_dicts.items()}
TypeError: Got unsupported ScalarType BFloat16

```
Numpy not support bfloat16. 

if convert bfloat16 to float32 , can't support float16 anymore. 
```python
all_dicts = {k: v.numpy() if v.dtype != torch.bfloat16else v.to(torch.float32).numpy() for k, v in all_dicts.items()}
```

maybe there have some more elegant method .

**Comment by leifu1128** [comment]
Are you converting a custom model?

**Comment by rockyzhengwu** [comment]
> Are you converting a custom model?

convert Llama2 7B , I downloaded from llama https://github.com/facebookresearch/llama

**Comment by LaurentMazare** [comment]
I don't think there is much need for this script anymore so I'll remove it as it is actually out of date. Instead you should rely on the autodownload of the weights that happens when running the llama example. You can use the `model-id` flag if you don't want to use the default model (which is llama2 7B).

**Comment by rockyzhengwu** [comment]
thanks
