### ISSUE TITLE
GPU not being used.

### ISSUE THREAD

**Issue by SubinVidhu** [huggingface/candle#540]
**SYSTEM: LINUX (Ubuntu 20.04 LTS)**

For LLaMA2, run the following command to retrieve the weight files and start a test server:

cd candle-wasm-examples/llama2-c
wget https://huggingface.co/spaces/lmz/candle-llama2/resolve/main/model.bin
wget https://huggingface.co/spaces/lmz/candle-llama2/resolve/main/tokenizer.json
trunk serve --release --public-url /candle-llama2/ --port 8081

**I have tried this out, and this is the output in my terminal:**

```
2023-08-21T11:41:29.012677Z  INFO  starting build
2023-08-21T11:41:29.013423Z  INFO spawning asset pipelines
2023-08-21T11:41:37.159986Z  INFO copying file path="tokenizer.json"
2023-08-21T11:41:37.160007Z  INFO copying file path="model.bin"
2023-08-21T11:41:37.160020Z  INFO building candle-wasm-example-llama2
2023-08-21T11:41:37.160056Z  INFO building candle-wasm-example-llama2
2023-08-21T11:41:37.161954Z  INFO finished copying file path="tokenizer.json"
2023-08-21T11:41:37.221128Z  INFO finished copying file path="model.bin"
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling wasm-bindgen-shared v0.2.87
   Compiling once_cell v1.18.0
   Compiling log v0.4.20
   Compiling bumpalo v3.13.0
   Compiling wasm-bindgen v0.2.87
   Compiling libc v0.2.147
   Compiling serde v1.0.185
   Compiling memchr v2.5.0
   Compiling crossbeam-utils v0.8.16
   Compiling itoa v1.0.9
   Compiling ryu v1.0.15
   Compiling serde_json v1.0.105
   Compiling scopeguard v1.2.0
   Compiling libm v0.2.7
   Compiling either v1.9.0
   Compiling syn v1.0.109
   Compiling rayon-core v1.11.0
   Compiling thiserror v1.0.47
   Compiling paste v1.0.14
   Compiling futures-core v0.3.28
   Compiling bytemuck v1.13.1
   Compiling lazy_static v1.4.0
   Compiling memoffset v0.9.0
   Compiling crossbeam-epoch v0.9.15
   Compiling num-traits v0.2.16
   Compiling reborrow v0.5.4
   Compiling futures-channel v0.3.28
   Compiling bitflags v1.3.2
   Compiling dyn-stack v0.9.0
   Compiling raw-cpuid v10.7.0
   Compiling num_cpus v1.16.0
   Compiling slab v0.4.8
   Compiling ppv-lite86 v0.2.17
   Compiling seq-macro v0.3.5
   Compiling futures-sink v0.3.28
   Compiling version_check v0.9.4
   Compiling futures-task v0.3.28
   Compiling ident_case v1.0.1
   Compiling crossbeam-channel v0.5.8
   Compiling pin-project-lite v0.2.12
   Compiling quote v1.0.33
   Compiling strsim v0.10.0
   Compiling fnv v1.0.7
   Compiling futures-util v0.3.28
   Compiling percent-encoding v2.3.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling syn v2.0.29
   Compiling crossbeam-deque v0.8.3
   Compiling form_urlencoded v1.2.0
   Compiling bytes v1.4.0
   Compiling rustversion v1.0.14
   Compiling futures-io v0.3.28
   Compiling anymap2 v0.13.0
   Compiling pin-utils v0.1.0
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.3
   Compiling prettyplease v0.1.25
   Compiling crc32fast v1.3.2
   Compiling aho-corasick v1.0.4
   Compiling http v0.2.9
   Compiling regex-syntax v0.7.4
   Compiling hashbrown v0.12.3
   Compiling tracing-core v0.1.31
   Compiling minimal-lexical v0.2.1
   Compiling rayon v1.7.0
   Compiling num-complex v0.4.4
   Compiling cc v1.0.83
   Compiling bit-vec v0.6.3
   Compiling boolinator v2.4.0
   Compiling byteorder v1.4.3
   Compiling esaxx-rs v0.1.8
   Compiling adler v1.0.2
   Compiling gimli v0.27.3
   Compiling zip v0.6.6
   Compiling miniz_oxide v0.7.1
   Compiling bit-set v0.5.3
   Compiling nom v7.1.3
   Compiling object v0.31.1
   Compiling itertools v0.8.2
   Compiling implicit-clone v0.3.6
   Compiling base64 v0.13.1
   Compiling macro_rules_attribute-proc_macro v0.1.3
   Compiling unicode-segmentation v1.10.1
   Compiling backtrace v0.3.68
   Compiling rustc-demangle v0.1.23
   Compiling regex-automata v0.3.6
   Compiling anyhow v1.0.75
   Compiling memmap2 v0.7.1
   Compiling smallvec v1.11.0
   Compiling macro_rules_attribute v0.1.3
   Compiling aho-corasick v0.7.20
   Compiling unicode-normalization-alignments v0.1.12
   Compiling itertools v0.9.0
   Compiling unicode_categories v0.1.1
   Compiling candle-gemm-common v0.15.6
   Compiling rayon-cond v0.1.0
   Compiling wasm-bindgen-backend v0.2.87
   Compiling darling_core v0.14.4
   Compiling candle-gemm-f32 v0.15.6
   Compiling candle-gemm-f64 v0.15.6
   Compiling candle-gemm-c64 v0.15.6
   Compiling candle-gemm-c32 v0.15.6
   Compiling addr2line v0.20.0
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling regex v1.9.3
   Compiling yew-macro v0.20.0
   Compiling fancy-regex v0.10.0
   Compiling serde_derive v1.0.185
   Compiling wasm-bindgen-macro v0.2.87
   Compiling thiserror-impl v1.0.47
   Compiling pin-project-internal v1.1.3
   Compiling futures-macro v0.3.28
   Compiling tracing-attributes v0.1.26
   Compiling darling_macro v0.14.4
   Compiling monostate-impl v0.1.9
   Compiling darling v0.14.4
   Compiling derive_builder_core v0.12.0
   Compiling js-sys v0.3.64
   Compiling console_error_panic_hook v0.1.7
   Compiling pin-project v1.1.3
   Compiling tracing v0.1.37
   Compiling derive_builder_macro v0.12.0
   Compiling derive_builder v0.12.0
   Compiling web-sys v0.3.64
   Compiling getrandom v0.2.10
   Compiling wasm-bindgen-futures v0.4.37
   Compiling gloo-timers v0.2.6
   Compiling rand_core v0.6.4
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling futures v0.3.28
   Compiling pinned v0.1.0
   Compiling rand_distr v0.4.3
   Compiling half v2.3.1
   Compiling candle-gemm-f16 v0.15.6
   Compiling candle-gemm v0.15.6
   Compiling bincode v1.3.3
   Compiling serde-wasm-bindgen v0.5.0
   Compiling serde_urlencoded v0.7.1
   Compiling monostate v0.1.9
   Compiling spm_precompiled v0.1.4
   Compiling safetensors v0.3.2
   Compiling tokenizers v0.13.4
   Compiling candle-core v0.1.2 (/home/protos/Desktop/delet/candle/candle-core)
   Compiling gloo-utils v0.1.7
   Compiling gloo-events v0.1.2
   Compiling gloo-dialogs v0.1.1
   Compiling gloo-render v0.1.1
   Compiling wasm-logger v0.2.0
   Compiling gloo-console v0.2.3
   Compiling gloo-storage v0.2.2
   Compiling gloo-net v0.3.1
   Compiling gloo-file v0.2.3
   Compiling gloo-history v0.1.5
   Compiling gloo-worker v0.2.1
   Compiling gloo-worker v0.1.2
   Compiling gloo v0.8.1
   Compiling prokio v0.1.0
   Compiling candle-nn v0.1.2 (/home/protos/Desktop/delet/candle/candle-nn)
   Compiling yew v0.20.0
   Compiling yew-agent v0.2.0
   Compiling candle-wasm-example-llama2 v0.1.2 (/home/protos/Desktop/delet/candle/candle-wasm-examples/llama2-c)
    Finished release [optimized] target(s) in 26.30s
2023-08-21T11:42:03.489906Z  INFO fetching cargo artifacts
   Compiling candle-wasm-example-llama2 v0.1.2 (/home/protos/Desktop/delet/candle/candle-wasm-examples/llama2-c)
    Finished release [optimized] target(s) in 26.51s
2023-08-21T11:42:03.705664Z  INFO fetching cargo artifacts
2023-08-21T11:42:03.714152Z  INFO processing WASM for worker
2023-08-21T11:42:03.720503Z  INFO using system installed binary app=wasm-bindgen version=0.2.87
2023-08-21T11:42:03.720633Z  INFO calling wasm-bindgen for worker
2023-08-21T11:42:03.815762Z  INFO processing WASM for app
2023-08-21T11:42:03.820115Z  INFO using system installed binary app=wasm-bindgen version=0.2.87
2023-08-21T11:42:03.820170Z  INFO calling wasm-bindgen for app
2023-08-21T11:42:03.851427Z  INFO copying generated wasm-bindgen artifacts
2023-08-21T11:42:03.853467Z  INFO downloading wasm-opt version="version_113"
2023-08-21T11:42:03.856656Z  INFO copying generated wasm-bindgen artifacts
2023-08-21T11:42:11.809384Z  INFO installing wasm-opt
2023-08-21T11:42:12.135916Z  INFO calling wasm-opt
2023-08-21T11:42:12.135948Z  INFO calling wasm-opt
2023-08-21T11:42:15.632514Z  INFO copying generated wasm-opt artifacts
2023-08-21T11:42:48.709221Z  INFO copying generated wasm-opt artifacts
2023-08-21T11:42:48.712131Z  INFO applying new distribution
2023-08-21T11:42:48.712631Z  INFO  success
2023-08-21T11:42:48.712722Z  INFO  serving static assets at -> /candle-llama2/
2023-08-21T11:42:48.712743Z  INFO  server listening at http://127.0.0.1:8081
```

I am able to access " http://localhost:8081/candle-llama2", **but my gpu is not being used.** 
Does this method ensure the support of GPU?
I have tried findind my compute_gap using `nvidia-smi --query-gpu=compute_cap --format=csv,noheader`, its 8.6 .

**Comment by LaurentMazare** [comment]
The wasm examples don't use your gpu at the moment.
You can use the command line examples if you want to run on gpu. For this you have to specify the `cuda` feature (and `cudnn` if installed, not that this last one provides some large speedup so is highly recommended). E.g.:
```bash
cargo run --profile=release-with-debug --features cuda,cudnn --example llama2-c -- inference
```

**Comment by SubinVidhu** [comment]
Thanks for replying.
I have tried out your command, but ends up with a new error.

```
Compiling serde_derive v1.0.185
   Compiling futures-macro v0.3.28
   Compiling tokio-macros v2.1.0
   Compiling ring v0.16.20
   Compiling openssl-macros v0.1.1
   Compiling tracing-attributes v0.1.26
   Compiling darling_core v0.14.4
   Compiling thiserror-impl v1.0.47
   Compiling candle-kernels v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle/candle-kernels)
   Compiling rustls v0.21.6
   Compiling cudarc v0.9.14
   Compiling memchr v2.5.0
   Compiling candle-gemm-f16 v0.15.6
   Compiling regex-automata v0.3.6
   Compiling portable-atomic v1.4.2
   Compiling onig_sys v69.8.1
error: failed to run custom build command for cudarc v0.9.14

Caused by:
  process didn't exit successfully: /home/protos/Desktop/Candle_HuggingFace/candle/target/release-with-debug/build/cudarc-f1a93ce04334efae/build-script-build (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=[build.rs](http://build.rs/)
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR
  cargo:rustc-link-search=native=/usr/local/cuda/lib64
  cargo:rustc-link-search=native=/usr/local/cuda/lib64/stubs
  cargo:rustc-link-search=native=/usr/local/cuda/targets/x86_64-linux
  cargo:rustc-link-search=native=/usr/local/cuda/targets/x86_64-linux/lib
  cargo:rustc-link-search=native=/usr/local/cuda/targets/x86_64-linux/lib/stubs
  cargo:rustc-link-lib=dylib=cuda
  cargo:rustc-link-lib=dylib=nvrtc
  cargo:rustc-link-lib=dylib=curand
  cargo:rustc-link-lib=dylib=cublas
  cargo:rustc-link-lib=dylib=cublasLt

  --- stderr
  thread 'main' panicked at 'Unable to find include/cudnn.h under any of: ["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]. Set the CUDNN_LIB environment variable to $CUDNN_LIB/include/cudnn.h to override path.', /home/protos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.9.14/build.rs:62:17
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by LaurentMazare** [comment]
You need to have cudnn installed to use the cudnn feature. You can remove it and just put `-- features cuda` if you only have cuda installed.

**Comment by SubinVidhu** [comment]
Is any specific version of cudnn required? This is my `nvcc -V` out: 

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

A documentation to install the required cudnn would be helpful, thanks in advance.

**Comment by LaurentMazare** [comment]
Looking at your first error message `Unable to find include/cudnn.h under any of: ["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda"...`, it seems that cudnn is not found at all, I don't think there would be any version issue anyway.

**Comment by SubinVidhu** [comment]
`cargo run --profile=release-with-debug --features cuda,cudnn --example llama2-c -- inference` , this is pretty fast. Thanks for replying.

I have ran the above line and got this as the output:
```
Finished release-with-debug [optimized + debuginfo] target(s) in 0.09s
     Running target/release-with-debug/examples/llama2-c inference
loading the model weights from karpathy/tinyllamas
Config { dim: 288, hidden_dim: 768, n_layers: 6, n_heads: 6, n_kv_heads: 6, vocab_size: 32000, seq_len: 256, norm_eps: 1e-5 }
starting the inference loop
 Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, red ball in the sky. It was the sun! She thought it was so pretty.
Lily wanted to play with the ball, but it was too high up in the sky. She tried to jump and reach it, but she couldn't. Then, she had an idea. She would use a stick to knock the ball down.
Lily found a stick and tried to hit the ball. But the stick was too short. She tried again and again, but she couldn't reach it. She felt sad.
Suddenly, a kind man came by and saw Lily. He asked her what was wrong. Lily told him about the ball. The man smiled and said, "I have a useful idea!" He took out a long stick and used it to knock the ball down. Lily was so happy! She thanked the man and they played together in the sunshine.<s> Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big,
256 tokens generated (359.85 token/s)
```

May I know where the prompt for this particular output was given?
Is there an option for CLI?
And Just a curious question as well, does this support Quantised 70B models? (planning to run it without `--features cuda,cudnn`)
Thanks in advance.

**Comment by SubinVidhu** [comment]
Tried running the `Llama-2-70b-chat.ggmlv3.q4_1.bin` from `TheBloke/Llama-2-70B-Chat-GGML`

```
Compiling candle-examples v0.1.2 (/home/protos/Desktop/delet/candle/candle-examples)
    Finished release [optimized] target(s) in 4.60s
     Running target/release/examples/quantized
avx: true, neon: false, simd128: false, f16c: true
..ama-2-70b-chat.ggmlv3.q4_1.bin [00:33:58] [██████████████████████████████████████████████████████████████████████████████████] 40.20 GiB/40.20 GiB 20.20 MiB/s (0s)loaded 723 tensors (43.17GB) in 203.45s
params: HParams { n_vocab: 32000, n_embd: 8192, n_mult: 4096, n_head: 64, n_layer: 80, n_rot: 128, ftype: 3 }
model built
thread 'main' panicked at 'not yet implemented', candle-core/src/quantized/k_quants.rs:1004:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Compiling candle-examples v0.1.2 (/home/protos/Desktop/delet/candle/candle-examples)
    Finished release [optimized] target(s) in 4.60s
     Running target/release/examples/quantized
avx: true, neon: false, simd128: false, f16c: true
..ama-2-70b-chat.ggmlv3.q4_1.bin [00:33:58] [██████████████████████████████████████████████████████████████████████████████████] 40.20 GiB/40.20 GiB 20.20 MiB/s (0s)loaded 723 tensors (43.17GB) in 203.45s
params: HParams { n_vocab: 32000, n_embd: 8192, n_mult: 4096, n_head: 64, n_layer: 80, n_rot: 128, ftype: 3 }
model built
thread 'main' panicked at 'not yet implemented', candle-core/src/quantized/k_quants.rs:1004:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

Ended up with the above error.

**Comment by LaurentMazare** [comment]
- llama2-c is a very small model trained to the tiny stories dataset as popularized by Andrej Karpathy [llama2.c](https://github.com/karpathy/llama2.c). That's why it's very fast, we also have a full llama implementation, see the `llama` example.
- For each example, you can run it with `-- --help` to get the arguments, usually there is a prompt and the help is likely to tell you its default value (otherwise you may want to glimpse at the code).
- We indeed have some quantization support, for now it only works on q4_0 ggml variants but more is to come soon via #524. I also just merged #545 which adds a `--which` flag to the quantized example which lets you try out larger variant. The 7b and 13b work fine for me, I don't have enough memory for the 70b though but hopefully it will work too. Typical usage:
```bash
cargo run --example quantized --profile=release-with-debug -- --prompt "My favorite theorem is "  --which 13b
```

**Comment by SubinVidhu** [comment]
`cargo run --example quantized --profile=release-with-debug -- --prompt "My favorite theorem is "  --which 13b` works and gives this output:

```
Finished release-with-debug [optimized + debuginfo] target(s) in 0.09s
     Running target/release-with-debug/examples/quantized --prompt 'My favorite theorem is ' --which 13b
avx: true, neon: false, simd128: false, f16c: true
loaded 363 tensors (7.32GB) in 3.62s
params: HParams { n_vocab: 32000, n_embd: 5120, n_mult: 256, n_head: 40, n_layer: 40, n_rot: 128, ftype: 2 }
model built
My favorite theorem is 1 + 1 = 2.
I'm not sure if I've ever seen a proof of it, but I'm pretty sure it's true.
I'm not sure if I've ever seen a proof of it, but I'm pretty sure it's true.
I'm not sure if I've ever seen a proof of it, but I'm pretty sure it's true. I'm not sure if I'

   6 prompt tokens processed: 4.45 token/s
  99 tokens generated: 3.27 token/s
```

But the when I run `cargo run --example quantized --profile=release-with-debug -- --prompt "My favorite theorem is "  --which 70b`, it ends up with the following error:
  ```
   Updating [crates.io](http://crates.io/) index
   Downloaded reqwest v0.11.19
   Downloaded h2 v0.3.21
   Downloaded 2 crates (321.7 KB) in 1.05s
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling once_cell v1.18.0
   Compiling bitflags v1.3.2
   Compiling libm v0.2.7
   Compiling crossbeam-utils v0.8.16
   Compiling lazy_static v1.4.0
   Compiling pkg-config v0.3.27
   Compiling itoa v1.0.9
   Compiling scopeguard v1.2.0
   Compiling serde v1.0.185
   Compiling rayon-core v1.11.0
   Compiling either v1.9.0
   Compiling paste v1.0.14
   Compiling pin-project-lite v0.2.12
   Compiling futures-core v0.3.28
   Compiling vcpkg v0.2.15
   Compiling bytemuck v1.13.1
   Compiling reborrow v0.5.4
   Compiling serde_json v1.0.105
   Compiling log v0.4.20
   Compiling ryu v1.0.15
   Compiling ppv-lite86 v0.2.17
   Compiling crc32fast v1.3.2
   Compiling memoffset v0.9.0
   Compiling num-traits v0.2.16
   Compiling crossbeam-epoch v0.9.15
   Compiling slab v0.4.8
   Compiling dyn-stack v0.9.0
   Compiling tracing-core v0.1.31
   Compiling crossbeam-channel v0.5.8
   Compiling raw-cpuid v10.7.0
   Compiling bytes v1.4.0
   Compiling quote v1.0.33
   Compiling futures-sink v0.3.28
   Compiling seq-macro v0.3.5
   Compiling syn v2.0.29
   Compiling crossbeam-deque v0.8.3
   Compiling futures-task v0.3.28
   Compiling futures-channel v0.3.28
   Compiling futures-util v0.3.28
   Compiling simd-adler32 v0.3.7
   Compiling syn v1.0.109
   Compiling cc v1.0.83
   Compiling num_cpus v1.16.0
   Compiling getrandom v0.2.10
   Compiling num-complex v0.4.4 
   Compiling mio v0.8.8
   Compiling rand_core v0.6.4
   Compiling socket2 v0.5.3
   Compiling rand_chacha v0.3.1
   Compiling foreign-types-shared v0.1.1
   Compiling futures-io v0.3.28
   Compiling adler v1.0.2
   Compiling untrusted v0.7.1
   Compiling rand v0.8.5
   Compiling pin-utils v0.1.0
   Compiling spin v0.5.2
   Compiling openssl v0.10.56
   Compiling miniz_oxide v0.7.1
   Compiling foreign-types v0.3.2
   Compiling indexmap v1.9.3
   Compiling rayon v1.7.0
   Compiling fnv v1.0.7
   Compiling thiserror v1.0.47
   Compiling ident_case v1.0.1
   Compiling tinyvec_macros v0.1.1
   Compiling strsim v0.10.0
   Compiling native-tls v0.2.11
   Compiling http v0.2.9
   Compiling rand_distr v0.4.3
   Compiling openssl-sys v0.9.91
   Compiling ring v0.16.20
   Compiling backtrace v0.3.68
   Compiling tinyvec v1.6.0
   Compiling httparse v1.8.0
   Compiling openssl-probe v0.1.5
   Compiling hashbrown v0.12.3
   Compiling percent-encoding v2.3.0
   Compiling half v2.3.1
   Compiling form_urlencoded v1.2.0
   Compiling byteorder v1.4.3
   Compiling try-lock v0.2.4
   Compiling unicode-bidi v0.3.13
   Compiling anyhow v1.0.75
   Compiling want v0.3.1
   Compiling http-body v0.4.5
   Compiling unicode-normalization v0.1.22
   Compiling onig_sys v69.8.1
   Compiling flate2 v1.0.27
   Compiling socket2 v0.4.9
   Compiling aho-corasick v1.0.4
   Compiling idna v0.4.0
   Compiling rustix v0.38.8
   Compiling candle-gemm-common v0.15.6
   Compiling portable-atomic v1.4.2
   Compiling candle-gemm-f32 v0.15.6
   Compiling candle-gemm-c32 v0.15.6
   Compiling candle-gemm-f64 v0.15.6
   Compiling candle-gemm-c64 v0.15.6
   Compiling httpdate v1.0.3
   Compiling gimli v0.27.3
   Compiling rustls v0.21.6
   Compiling darling_core v0.14.4
   Compiling smallvec v1.11.0
   Compiling candle-gemm-f16 v0.15.6
   Compiling tower-service v0.3.2
   Compiling regex-syntax v0.7.4
   Compiling url v2.4.0
   Compiling object v0.31.1
   Compiling serde_derive v1.0.185
   Compiling futures-macro v0.3.28
   Compiling tokio-macros v2.1.0
   Compiling openssl-macros v0.1.1
   Compiling tracing-attributes v0.1.26
   Compiling tokio v1.32.0
   Compiling thiserror-impl v1.0.47
   Compiling tracing v0.1.37
   Compiling darling_macro v0.14.4
   Compiling sct v0.7.0
   Compiling rustls-webpki v0.101.3
   Compiling rustls-webpki v0.100.1
   Compiling darling v0.14.4
   Compiling derive_builder_core v0.12.0
   Compiling regex-automata v0.3.6
   Compiling addr2line v0.20.0
   Compiling candle-gemm v0.15.6
   Compiling zip v0.6.6
   Compiling memmap2 v0.7.1
   Compiling num-integer v0.1.45
   Compiling minimal-lexical v0.2.1
   Compiling bit-vec v0.6.3
   Compiling unicode-width v0.1.10
   Compiling tokio-util v0.7.8
   Compiling tokio-native-tls v0.3.1
   Compiling linux-raw-sys v0.4.5
   Compiling rustc-demangle v0.1.23
   Compiling option-ext v0.2.0
   Compiling esaxx-rs v0.1.8
   Compiling base64 v0.21.2
   Compiling bitflags v2.4.0
   Compiling h2 v0.3.21
   Compiling derive_builder_macro v0.12.0
   Compiling dirs-sys v0.4.1
   Compiling nom v7.1.3
   Compiling regex v1.9.3
   Compiling serde_urlencoded v0.7.1
   Compiling bit-set v0.5.3
   Compiling console v0.15.7
   Compiling futures-executor v0.3.28
   Compiling webpki-roots v0.23.1
   Compiling monostate-impl v0.1.9
   Compiling safetensors v0.3.2
   Compiling num-rational v0.4.1
   Compiling candle-core v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-core)
   Compiling hyper v0.14.27
   Compiling itertools v0.8.2
   Compiling encoding_rs v0.8.32
   Compiling unicode-segmentation v1.10.1
   Compiling utf8parse v0.2.1
   Compiling mime v0.3.17
   Compiling number_prefix v0.4.0
   Compiling ipnet v2.8.0
   Compiling base64 v0.13.1
   Compiling macro_rules_attribute-proc_macro v0.1.3
   Compiling spm_precompiled v0.1.4
   Compiling onig v6.4.0
   Compiling candle-nn v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-nn)
   Compiling macro_rules_attribute v0.1.3
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.19
   Compiling indicatif v0.17.6
   Compiling anstyle-parse v0.2.1
   Compiling ureq v2.7.1
   Compiling rayon-cond v0.1.0
   Compiling monostate v0.1.9
   Compiling is-terminal v0.4.9
   Compiling futures v0.3.28
   Compiling fancy-regex v0.10.0
   Compiling derive_builder v0.12.0
   Compiling dirs v5.0.1
   Compiling unicode-normalization-alignments v0.1.12
   Compiling fdeflate v0.3.0
   Compiling aho-corasick v0.7.20
   Compiling itertools v0.9.0
   Compiling anstyle-query v1.0.0
   Compiling unicode_categories v0.1.1
   Compiling overload v0.1.1
   Compiling colorchoice v1.0.0
   Compiling riff v1.0.1
   Compiling anstyle v1.0.1
   Compiling wav v1.0.0
   Compiling anstream v0.3.2
   Compiling tokenizers v0.13.4
   Compiling nu-ansi-term v0.46.0
   Compiling png v0.17.10
   Compiling hf-hub v0.2.0
   Compiling candle-examples v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-examples)
   Compiling tracing-log v0.1.3
   Compiling thread_local v1.1.7
   Compiling sharded-slab v0.1.4
   Compiling clap_lex v0.5.0
   Compiling jpeg-decoder v0.3.0
   Compiling heck v0.4.1
   Compiling color_quant v1.1.0
   Compiling image v0.24.7
   Compiling tracing-subscriber v0.3.17
   Compiling clap_builder v4.3.23
   Compiling candle-core v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-core)
   Compiling hyper v0.14.27
   Compiling itertools v0.8.2
   Compiling encoding_rs v0.8.32
   Compiling unicode-segmentation v1.10.1
   Compiling utf8parse v0.2.1
   Compiling mime v0.3.17
   Compiling number_prefix v0.4.0
   Compiling ipnet v2.8.0
   Compiling base64 v0.13.1
   Compiling macro_rules_attribute-proc_macro v0.1.3
   Compiling spm_precompiled v0.1.4
   Compiling onig v6.4.0
   Compiling candle-nn v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-nn)
   Compiling macro_rules_attribute v0.1.3
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.19
   Compiling indicatif v0.17.6
   Compiling anstyle-parse v0.2.1
   Compiling ureq v2.7.1
   Compiling rayon-cond v0.1.0
   Compiling monostate v0.1.9
   Compiling is-terminal v0.4.9
   Compiling futures v0.3.28
   Compiling fancy-regex v0.10.0
   Compiling derive_builder v0.12.0
   Compiling dirs v5.0.1
   Compiling unicode-normalization-alignments v0.1.12
   Compiling fdeflate v0.3.0
   Compiling aho-corasick v0.7.20
   Compiling itertools v0.9.0
   Compiling anstyle-query v1.0.0
   Compiling unicode_categories v0.1.1
   Compiling overload v0.1.1
   Compiling colorchoice v1.0.0
   Compiling riff v1.0.1
   Compiling anstyle v1.0.1
   Compiling wav v1.0.0
   Compiling anstream v0.3.2
   Compiling tokenizers v0.13.4
   Compiling nu-ansi-term v0.46.0
   Compiling png v0.17.10
   Compiling hf-hub v0.2.0
   Compiling candle-examples v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-examples)
   Compiling tracing-log v0.1.3
   Compiling thread_local v1.1.7
   Compiling sharded-slab v0.1.4
   Compiling clap_lex v0.5.0
   Compiling jpeg-decoder v0.3.0
   Compiling heck v0.4.1
   Compiling color_quant v1.1.0
   Compiling image v0.24.7
   Compiling tracing-subscriber v0.3.17
   Compiling clap_builder v4.3.23
   Compiling clap_derive v4.3.12
   Compiling candle-datasets v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-datasets)
   Compiling candle-transformers v0.1.2 (/home/protos/Desktop/Candle_HuggingFace/candle_22_8_23/candle/candle-transformers)
   Compiling tracing-chrome v0.7.1
   Compiling clap v4.3.23
    Finished release-with-debug [optimized + debuginfo] target(s) in 1m 14s
     Running target/release-with-debug/examples/quantized --prompt 'My favorite theorem is ' --which 70b
avx: true, neon: false, simd128: false, f16c: true
llama-2-70b.ggmlv3.q4_0.bin [00:31:13] [████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 36.20 GiB/36.20 GiB 19.78 MiB/s (0s)loaded 723 tensors (38.87GB) in 93.98s
params: HParams { n_vocab: 32000, n_embd: 8192, n_mult: 4096, n_head: 64, n_layer: 80, n_rot: 128, ftype: 2 }
model built
tokenizer.json [00:00:01] [████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 1.76 MiB/1.76 MiB 1.32 MiB/s (0s)Error: shape mismatch in reshape, lhs: [1, 6, 1024], rhs: [1, 6, 64, 128]
My favorite theorem is
```

Hope this gets solved as well.

**Comment by LLukas22** [comment]
llama-2-70B uses a slight architectural tweak, which currently isn't implemented. But that should be easy to implement.

**Comment by LaurentMazare** [comment]
Closing this one as everything should be in order now, feel free to open a new issue if you run into further problems.
