### ISSUE TITLE
Very slow softmax when using mkl.

### ISSUE THREAD

**Issue by LaurentMazare** [huggingface/candle#583]
When running the stable-diffusion example (default settings) on cpu on my Ryzen 2600X (32G memory) with the `mkl` feature enabled I noticed the following:
- ~50% of the time is spent in softmaxs.
- More weirdly the two last large softmaxes in the unet up part account for most of it, they run in ~20s.
- However there are other softmaxes using the same shape/stride/dtype that run in ~4s, including one just before these calls.
- The resident memory usage increases significantly during the softmax call, raising to ~15GB.
- Attaching a gdb to the process at that time, it seems that the time is spent in the vectorized exp operation.
- Using the [LD_PRELOAD trick](https://danieldk.eu/mkl-amd-zen/) did not help.
- Tweaking the number of threads did not help.
- Using jemalloc did not help.

Unsure where to go from here, so making an issue to summarize this. Interested to know if anyone else saw the same kind of thing.

mkl version: 2023.1.0.

Some trace details, printing the memory usage just before the softmax and the timings just after.
```
Ok(Statm { size: 2142641, resident: 1844850, share: 3195, text: 6340, data: 1861406 })                                                                                                                                                                        
Layout { shape: [10, 9216, 9216], stride: [84934656, 9216, 1], start_offset: 0 } 3.783596196s                                                                                                                                                                 
Ok(Statm { size: 1302850, resident: 1005097, share: 3195, text: 6340, data: 1021615 })                                                                                                                                                                        
Layout { shape: [10, 9216, 77], stride: [709632, 77, 1], start_offset: 0 } 37.607104ms                                                                                                                                                                        
Ok(Statm { size: 2150833, resident: 1853137, share: 3195, text: 6340, data: 1869598 })                                                                                                                                                                        
Layout { shape: [10, 9216, 9216], stride: [84934656, 9216, 1], start_offset: 0 } 3.977735836s                                                                                                                       
Ok(Statm { size: 1311042, resident: 1013320, share: 3195, text: 6340, data: 1029807 })                                                                                                                              
Layout { shape: [10, 9216, 77], stride: [709632, 77, 1], start_offset: 0 } 41.340855ms                                                                                                                              
Ok(Statm { size: 1410226, resident: 1110083, share: 3195, text: 6340, data: 1128991 })                                                                                                                              
Layout { shape: [20, 2304, 2304], stride: [5308416, 2304, 1], start_offset: 0 } 505.919303ms                                                                                                                        
Ok(Statm { size: 1297905, resident: 997784, share: 3195, text: 6340, data: 1016670 })                                                                                                                               
Layout { shape: [20, 2304, 77], stride: [177408, 77, 1], start_offset: 0 } 19.462834ms                                                                                                                              
Ok(Statm { size: 1413106, resident: 1112886, share: 3195, text: 6340, data: 1131871 })                                                                                                                              
Layout { shape: [20, 2304, 2304], stride: [5308416, 2304, 1], start_offset: 0 } 513.93255ms                                                                                                                         
Ok(Statm { size: 1300785, resident: 1000586, share: 3195, text: 6340, data: 1019550 })                                                                                                                              
Layout { shape: [20, 2304, 77], stride: [177408, 77, 1], start_offset: 0 } 17.797312ms                                                                                                                              
Ok(Statm { size: 1307986, resident: 1007891, share: 3195, text: 6340, data: 1026751 })                                                                                                                              
Layout { shape: [40, 576, 576], stride: [331776, 576, 1], start_offset: 0 } 67.065747ms                                                                                                                             
Ok(Statm { size: 1297905, resident: 997734, share: 3195, text: 6340, data: 1016670 })                                                                                                                               
Layout { shape: [40, 576, 77], stride: [44352, 77, 1], start_offset: 0 } 4.158629ms                                                                                                                                 
Ok(Statm { size: 1314130, resident: 1011941, share: 3195, text: 6340, data: 1032895 })                                                                                                                              
Layout { shape: [40, 576, 576], stride: [331776, 576, 1], start_offset: 0 } 69.003847ms                                                                                                                             
Ok(Statm { size: 1301169, resident: 1000596, share: 3195, text: 6340, data: 1019934 })                                                                                                                              
Layout { shape: [40, 576, 77], stride: [44352, 77, 1], start_offset: 0 } 4.308189ms                       
Ok(Statm { size: 1304881, resident: 1004842, share: 3195, text: 6340, data: 1023646 })                                                                                                                              
Layout { shape: [40, 144, 144], stride: [20736, 144, 1], start_offset: 0 } 1.87685ms                                                                                                                                
Ok(Statm { size: 1304881, resident: 1004842, share: 3195, text: 6340, data: 1023646 })                    
Layout { shape: [40, 144, 77], stride: [11088, 77, 1], start_offset: 0 } 1.266164ms                                                                                                                                 
Ok(Statm { size: 1313746, resident: 1013425, share: 3195, text: 6340, data: 1032511 })                                                                                                                              
Layout { shape: [40, 576, 576], stride: [331776, 576, 1], start_offset: 0 } 66.710478ms                                                                                                                             
Ok(Statm { size: 1303665, resident: 1003452, share: 3195, text: 6340, data: 1022430 })                                                                                                                              
Layout { shape: [40, 576, 77], stride: [44352, 77, 1], start_offset: 0 } 4.084059ms                       
Ok(Statm { size: 1313746, resident: 1013460, share: 3195, text: 6340, data: 1032511 })                    
Layout { shape: [40, 576, 576], stride: [331776, 576, 1], start_offset: 0 } 66.646828ms                   
Ok(Statm { size: 1303665, resident: 1003421, share: 3195, text: 6340, data: 1022430 })                    
Layout { shape: [40, 576, 77], stride: [44352, 77, 1], start_offset: 0 } 4.228318ms                       
Ok(Statm { size: 1320722, resident: 1020511, share: 3195, text: 6340, data: 1039487 })                    
Layout { shape: [40, 576, 576], stride: [331776, 576, 1], start_offset: 0 } 70.34615ms       
Ok(Statm { size: 1307761, resident: 1007583, share: 3195, text: 6340, data: 1026526 })       
Layout { shape: [40, 576, 77], stride: [44352, 77, 1], start_offset: 0 } 4.248339ms          
Ok(Statm { size: 1424626, resident: 1124398, share: 3195, text: 6340, data: 1143391 })       
Layout { shape: [20, 2304, 2304], stride: [5308416, 2304, 1], start_offset: 0 } 506.180951ms  
Ok(Statm { size: 1315770, resident: 1015677, share: 3195, text: 6340, data: 1034535 })                    
Layout { shape: [20, 2304, 77], stride: [177408, 77, 1], start_offset: 0 } 17.490782ms                                                                                                                              
Ok(Statm { size: 1424626, resident: 1124334, share: 3195, text: 6340, data: 1143391 })      
Layout { shape: [20, 2304, 2304], stride: [5308416, 2304, 1], start_offset: 0 } 506.618845ms              
Ok(Statm { size: 1315770, resident: 1015599, share: 3195, text: 6340, data: 1034535 })                    
Layout { shape: [20, 2304, 77], stride: [177408, 77, 1], start_offset: 0 } 17.631262ms                                                                                                                              
Ok(Statm { size: 1429846, resident: 1129702, share: 3195, text: 6340, data: 1148611 })                                                                                                                              
Layout { shape: [20, 2304, 2304], stride: [5308416, 2304, 1], start_offset: 0 } 521.125569ms              
Ok(Statm { size: 1315770, resident: 1015521, share: 3195, text: 6340, data: 1034535 })                                                                                                                              
Layout { shape: [20, 2304, 77], stride: [177408, 77, 1], start_offset: 0 } 18.030219ms                                                                                                                              
Ok(Statm { size: 2170547, resident: 1870456, share: 3195, text: 6340, data: 1889312 })                    
Layout { shape: [10, 9216, 9216], stride: [84934656, 9216, 1], start_offset: 0 } 3.711185357s             
Ok(Statm { size: 1330756, resident: 1030645, share: 3195, text: 6340, data: 1049521 })                    
Layout { shape: [10, 9216, 77], stride: [709632, 77, 1], start_offset: 0 } 35.945209ms                    
Ok(Statm { size: 2170547, resident: 1870328, share: 3195, text: 6340, data: 1889312 })                                                                                                                              
Layout { shape: [10, 9216, 9216], stride: [84934656, 9216, 1], start_offset: 0 } 22.340766089s            
Ok(Statm { size: 1330756, resident: 1030601, share: 3195, text: 6340, data: 1049521 })                    
Layout { shape: [10, 9216, 77], stride: [709632, 77, 1], start_offset: 0 } 44.622953ms                                         
Ok(Statm { size: 2170547, resident: 1870434, share: 3195, text: 6340, data: 1889312 })                                         
Layout { shape: [10, 9216, 9216], stride: [84934656, 9216, 1], start_offset: 0 } 18.047176183s                                 
Ok(Statm { size: 1330756, resident: 1030641, share: 3195, text: 6340, data: 1049521 })                                         
Layout { shape: [10, 9216, 77], stride: [709632, 77, 1], start_offset: 0 } 37.916835ms                                         
step 2/30 done, 113.33s                                        
```

Gdb backtrace:
```
bt
#0  0x000055da68284105 in mkl_vml_kernel_sExp_EXHAynn ()
#1  0x000055da67ec0e29 in mkl_vml_serv_threader_s_1i_1o ()
#2  0x00007f962335ff13 in __kmp_invoke_microtask () from /opt/intel/oneapi/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libiomp5.so
#3  0x00007f96232ceef3 in __kmp_invoke_task_func (gtid=1768261824) at ../../src/kmp_runtime.cpp:7845
#4  0x00007f96232d0178 in __kmp_fork_call (loc=0x55da696588c0 <vsexp_data+768>, gtid=6656, call_context=(fork_context_last | unknown: 0x1a00), argc=704, microtask=0x77097d0, invoker=0x0, ap=0x7ffc28b61190)
    at ../../src/kmp_runtime.cpp:2508
#5  0x00007f9623288d23 in __kmpc_fork_call (loc=0x55da696588c0 <vsexp_data+768>, argc=6656, microtask=0x1a02) at ../../src/kmp_csupport.cpp:350
#6  0x000055da67ec0ba7 in mkl_vml_serv_threader_s_1i_1o ()
#7  0x000055da67ebcf24 in vsExp ()
#8  0x000055da67e5598b in candle_core::mkl::vs_exp (a=..., y=...) at candle-core/src/mkl.rs:190
#9  candle_core::op::{impl#39}::f32_vec (xs=..., ys=...) at candle-core/src/op.rs:479
#10 core::ops::function::FnMut::call_mut<fn(&[f32], &mut [f32]), (&[f32], &mut [f32])> () at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:166
#11 candle_core::cpu_backend::unary_map_vec<f32, f32, fn(f32) -> f32, fn(&[f32], &mut [f32])> (vs=..., layout=<optimized out>, f=<optimized out>, f_vec=<optimized out>) at candle-core/src/cpu_backend.rs:410
#12 candle_core::cpu_backend::{impl#19}::unary_impl<candle_core::op::Exp> (self=<optimized out>, layout=<optimized out>) at candle-core/src/cpu_backend.rs:1877
#13 0x000055da67df7090 in candle_core::storage::Storage::unary_impl<candle_core::op::Exp> (layout=0x1a02, self=<optimized out>) at candle-core/src/storage.rs:202
#14 candle_core::tensor::Tensor::exp (self=<optimized out>) at candle-core/src/tensor.rs:81
#15 0x000055da67ab497d in candle_nn::ops::softmax<candle_core::shape::D> (xs=0x7ffc28b617b8, dim=<optimized out>) at candle-nn/src/ops.rs:22
#16 0x000055da67a84ffe in stable_diffusion::attention::CrossAttention::attention (self=0x55da8258db30, query=<optimized out>, key=<optimized out>, value=<optimized out>)
    at candle-examples/examples/stable-diffusion/attention.rs:203
#17 0x000055da67a85f81 in stable_diffusion::attention::CrossAttention::forward (self=0x55da8258db30, xs=<optimized out>, context=...) at candle-examples/examples/stable-diffusion/attention.rs:230
#18 0x000055da67a886f5 in stable_diffusion::attention::BasicTransformerBlock::forward (self=0x55da8258db30, xs=..., context=...) at candle-examples/examples/stable-diffusion/attention.rs:295
#19 stable_diffusion::attention::SpatialTransformer::forward (self=0x55daac785c40, xs=0x7ffc28b61c58, context=...) at candle-examples/examples/stable-diffusion/attention.rs:423
#20 0x000055da67ae5c47 in stable_diffusion::unet_2d_blocks::CrossAttnUpBlock2D::forward (self=0x55da6fe905b0, xs=<optimized out>, res_xs=..., temb=..., upsample_size=..., encoder_hidden_states=...)
    at candle-examples/examples/stable-diffusion/unet_2d_blocks.rs:853
#21 0x000055da67a787bb in stable_diffusion::unet_2d::UNet2DConditionModel::forward_with_additional_residuals (self=0x7ffc28b62c60, xs=..., timestep=<optimized out>, encoder_hidden_states=<optimized out>, 
    down_block_additional_residuals=..., mid_block_additional_residual=...) at candle-examples/examples/stable-diffusion/unet_2d.rs:376
#22 stable_diffusion::unet_2d::UNet2DConditionModel::forward (self=0x7ffc28b62c60, xs=<optimized out>, timestep=<optimized out>, encoder_hidden_states=<optimized out>)
    at candle-examples/examples/stable-diffusion/unet_2d.rs:295
#23 0x000055da67ad1694 in stable_diffusion::run (args=...) at candle-examples/examples/stable-diffusion/main.rs:323
#24 0x000055da67ad42c1 in stable_diffusion::main () at candle-examples/examples/stable-diffusion/main.rs:359
```

![image](https://github.com/huggingface/candle/assets/1041292/65ee85ba-5924-4c34-b935-0e3e895f41eb)

**Comment by LaurentMazare** [comment]
![image](https://github.com/huggingface/candle/assets/1041292/5c23093b-fab0-4948-aad9-60828e428d4a)

This is the trace for a stable diffusion run with a single step. Softmax is also far from ideal here, also the conv2d used in the last decoding steps could be made a lot better.
