### ISSUE TITLE
Segmentation fault while running Stable Diffusion Example with Flash Attention

### ISSUE THREAD

**Issue by timothyman** [huggingface/candle#584]
Stable diffusion correctly outputs a generated image, but I encountered a **Segmentation fault** while trying to run the stable diffusion example with flash attention. I used the following command mentioned in [this comment](https://github.com/huggingface/candle/issues/567#issuecomment-1690011960) 
```
RUST_BACKTRACE=1 cargo run --example stable-diffusion --profile=release-with-debug --features cudnn --features flash-attn -- --prompt "a photorealistic very rusty robot" --use-flash-attn
```
but it also shows up using only cuda. I can't test it without Flash Attention, because I am running out of VRAM even when using `--use-f16`.

I am using WSL2 on Windows with CUDA version 11.8 and a RTX 3060 (`compute_cap == 8.6`). 

The output of `rustc --version` is:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
```

The output of `nvcc --version` is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

Here's the output on my console:

```
Building the Clip transformer.
Building the autoencoder.
Building the unet.
starting sampling
step 1/30 done, 1.42s
step 2/30 done, 0.79s
[...]
step 30/30 done, 0.80s
Generating the final image for sample 1/1.
Segmentation fault
```
Unfortunately, I don't have more output. Would be happy to further investigate if I am able to get some pointers on the how.

**Comment by LaurentMazare** [comment]
Not sure how easy it is to do on windows but could you try running it on gdb and reporting the backtrace? That would be very helpful.
Also maybe try with a smaller width/height (these are command line parameters) to see if it's mostly running out of memory or something else.

For running gdb on linux I would do:
```
gdb --args target/release-with-debug/examples/stable-diffusion --prompt 'a photorealistic very rusty robot' --use-flash-attn
```
Then at the gdb prompt enter "run", then wait for it to segfault and enter "bt", this should print the backtrace.

**Comment by timothyman** [comment]
Here it is:
```
Thread 1 "stable-diffusio" received signal SIGSEGV, Segmentation fault.
0x00007fffc174e8ad in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
(gdb) bt
#0  0x00007fffc174e8ad in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#1  0x00007fffc154d0c3 in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#2  0x00007fffc17c83c7 in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#3  0x00007fffc15b1e5e in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#4  0x00007fffc15b2788 in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#5  0x00007fffc15b2b11 in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#6  0x00007fffc14f8255 in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#7  0x00007fffc14f850f in ?? () from /usr/lib/wsl/drivers/nv_dispui.inf_amd64_f2b06cc19dadc00f/libcuda.so.1.1
#8  0x00007ffff7ffd060 in ?? () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000000 in ?? ()
```

**Comment by timothyman** [comment]
I also ran a 80x80 generation without Flash Attention with cuDNN and there is no Segfault there.

**Comment by LaurentMazare** [comment]
Thanks, sadly the backtrace doesn't tell us much besides the segfault taking place in the cuda driver.

**Comment by timothyman** [comment]
Yes, it's probably something in my CUDA setup.

Regardless, many thanks for the rapid responses. And apologies for the distraction.
