### ISSUE TITLE
Explicit panic on Falcon

### ISSUE THREAD

**Issue by noahgift** [huggingface/candle#593]
Hi,

I have most models to work with; thanks again for your guidance, but I also had one other issue with Falcon.  Hopefully, someone knows about this.

```
codespace@codespaces-f226cf:/workspaces/rust-candle-demos/candle$ RUST_BACKTRACE=1 && cargo run --example falcon --release -- --pr
ompt "which 100m sprinter won the 1984 olympics"?
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/examples/falcon --prompt 'which 100m sprinter won the 1984 olympics?'`
Running on CPU, to run on GPU, build this example with `--features cuda`
retrieved the files in 226.6µs
loaded the model in 8.0565019s
starting the inference loop
thread 'main' panicked at 'explicit panic', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-gemm-0.15.6/src/gemm.rs:143:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LaurentMazare** [comment]
That's because the model use `bf16` for which there is no cpu implementation. I'll make the error message more explicit, if you have a gpu maybe you want to use `--features cuda`?

**Comment by LaurentMazare** [comment]
Or you can try `--use-f32` if you have lots of memory :)

**Comment by noahgift** [comment]
> Or you can try `--use-f32` if you have lots of memory :)

That worked!  These GPU boxes from GitHub Codespaces for pretty crazy memory:

```
codespace@codespaces-f226cf:/workspaces/rust-candle-demos$ free -h
              total        used        free      shared  buff/cache   available
Mem:          110Gi        31Gi        44Gi       4.0Mi        33Gi        77Gi
Swap:            0B          0B          0B
```

```
codespace@codespaces-f226cf:/workspaces/rust-candle-demos/candle$ RUST_BACKTRACE=1 && cargo run --example falcon --release -- --prompt "which 100m sprinter won the 1984 olympics"? --use-f32
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished release [optimized] target(s) in 0.19s
     Running `target/release/examples/falcon --prompt 'which 100m sprinter won the 1984 olympics?' --use-f32`
Running on CPU, to run on GPU, build this example with `--features cuda`
retrieved the files in 218.6µs
loaded the model in 17.0826025s
starting the inference loop
> 2.6911119s
1 token: 193 '
```

**Comment by noahgift** [comment]
> That's because the model use `bf16` for which there is no cpu implementation. I'll make the error message more explicit, if you have a gpu maybe you want to use `--features cuda`?

Good to know!  Yes, the plan is for me to mostly use GPU to work with Candle.

These boxes do have CUDA working and I was able to get your previous library [Rust PyTorch](https://github.com/LaurentMazare/tch-rs) working well with them.  I am not an expert at configuring GPU in GitHub Codespaces by my contact at Microsoft is an expert and he promised to help fix this configuration, I will add him to this ticket.

```
codespace@codespaces-f226cf:/workspaces/rust-candle-demos/candle$ nvidia-smi 
Thu Aug 24 22:22:40 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           On  | 00000001:00:00.0 Off |                  Off |
| N/A   31C    P0              23W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by LaurentMazare** [comment]
You probably already tried it but using `--features cuda` might work well out of the box if cuda is installed at some default locations. E.g.
```bash
RUST_BACKTRACE=1 cargo run --example falcon --features cuda --release -- --prompt ...
```

**Comment by noahgift** [comment]
> You probably already tried it but using `--features cuda` might work well out of the box if cuda is installed at some default locations. E.g.
> 
> ```shell
> RUST_BACKTRACE=1 cargo run --example falcon --features cuda --release -- --prompt ...
> ```

I believe this is an error on my CUDA configuration which I am working on fixing (Codespaces are bit tricky to get perfect but once you do they are pretty cool because you can "fork" the environment and GPU "just works".  

```
codespace@codespaces-f226cf:/workspaces/rust-candle-demos/candle$ RUST_BACKTRACE=1 cargo run --example falcon --features cuda --release -- --prompt "What is an apple"
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling rayon v1.7.0
   Compiling cudarc v0.9.14
   Compiling candle-examples v0.1.3 (/workspaces/rust-candle-demos/candle/candle-examples)
error: failed to run custom build command for `cudarc v0.9.14`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/workspaces/rust-candle-demos/candle/target/release/build/cudarc-4b11c4da84f29f3d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to find `include/cuda.h` under any of: ["/usr", "/usr/local/cuda", "/opt/cuda", "/usr/lib/cuda", "C:/Program Files/NVIDIA GPU Computing Toolkit", "C:/CUDA"]. Set the `CUDA_ROOT` environment variable to `$CUDA_ROOT/include/cuda.h` to override path.', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.9.14/build.rs:21:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
     1: core::panicking::panic_fmt
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
     2: build_script_build::link_cuda::{{closure}}
     3: core::option::Option<T>::unwrap_or_else
     4: build_script_build::link_cuda
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `candle-examples v0.1.3 (/workspaces/rust-candle-demos/candle/candle-examples)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/workspaces/rust-candle-demos/candle/target/release/build/candle-examples-f3567e9c5827622f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  Error: cannot find include/cuda.h

  Stack backtrace:
     0: build_script_build::set_cuda_include_dir
     1: build_script_build::main
     2: core::ops::function::FnOnce::call_once
     3: std::sys_common::backtrace::__rust_begin_short_backtrace
     4: std::rt::lang_start::{{closure}}
     5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
        std::panicking::try::do_call
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
        std::panicking::try
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
        std::panic::catch_unwind
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
        std::rt::lang_start_internal::{{closure}}
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
        std::panicking::try::do_call
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
        std::panicking::try
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
        std::panic::catch_unwind
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
        std::rt::lang_start_internal
               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
     6: std::rt::lang_start
     7: main
     8: __libc_start_main
               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
     9: _start
codespace@codespaces-f226cf:/workspaces/rust-candle-demos/candle$
```

**Comment by LaurentMazare** [comment]
Ah yes certainly looks like a cuda setup issue with cudarc not finding `include/cuda.h`. Typical install would be in `/usr/local/cuda` but maybe this is different in your setup (the error message mentions the list of paths that were searched for this file and some useful enviroment variables in case you want to use some custom location, e.g. `CUDA_ROOT`).

**Comment by noahgift** [comment]
> Ah yes certainly looks like a cuda setup issue with cudarc not finding `include/cuda.h`. Typical install would be in `/usr/local/cuda` but maybe this is different in your setup (the error message mentions the list of paths that were searched for this file and some useful enviroment variables in case you want to use some custom location, e.g. `CUDA_ROOT`).

Thanks again for all of your help, I was able to make significant progress and get CUDA working in GitHub Codespaces due the help from @alfredo deza.  This is a repo that has a GitHub Codespace that should work for the majority of candle examples:  [Candle Demos .devcontainer](https://github.com/nogibjj/rust-candle-demos/tree/main/.devcontainer)

The main issue was the following:
* `sudo apt-get install cuda-nvcc-12-2`
* `export PATH=$PATH:/usr/local/cuda-12.2/bin`
* `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`
* `sudo apt-get install cuda-toolkit-12-2`

I verified that most candle demos including `whisper` and `big code` and `bert` work.  I still have an issue with Falcon:

```
codespace@codespaces-ac540e:/workspaces/rust-candle-demos/candle$ RUST_BACKTRACE=1 cargo run --features cuda --example falcon --release -- --prompt "What is the best ty
pe of Apple to eat"?
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished release [optimized] target(s) in 0.67s
     Running `target/release/examples/falcon --prompt 'What is the best type of Apple to eat?'`
retrieved the files in 254µs
loaded the model in 8.1835721s
starting the inference loop
Error: DriverError(CUDA_ERROR_NOT_FOUND, "named symbol not found") when loading is_u32_bf16

Stack backtrace:
   0: falcon::model::Falcon::forward
   1: falcon::TextGeneration::run
   2: falcon::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
   6: main
   7: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
   8: _start
```

**Comment by LaurentMazare** [comment]
Re `is_u32_bf16` missing, this may be caused by having an old GPU that doesn't support old bf16, we require cuda-arch >= 800 for these. Could you check your compute cap by running `nvidia-smi --query-gpu=compute_cap --format=csv`?

**Comment by noahgift** [comment]
> Re `is_u32_bf16` missing, this may be caused by having an old GPU that doesn't support old bf16, we require cuda-arch >= 800 for these. Could you check your compute cap by running `nvidia-smi --query-gpu=compute_cap --format=csv`?

codespace@codespaces-ac540e:/workspaces/rust-candle-demos/candle$ nvidia-smi --query-gpu=compute_cap --format=csv
compute_cap
7.0

**Comment by LaurentMazare** [comment]
Yep I'm afraid that explains it, we could convert the ops to take place in f16 but then might easily run into precision issues.

**Comment by noahgift** [comment]
> Yep I'm afraid that explains it, we could convert the ops to take place in f16 but then might easily run into precision issues.

No problem!  Feel free to close ticket.  Related I also have a lot of money to spend on AWS.  If anyone has advice on AWS GPU setup for development that would recommend let me know...otherwise, will most likely provision an EC2 Spot instance with a Custom AMI that has all of the CUDA stuff hooked up.  I might go Ubuntu for this since I could mimick a similar setup as GitHub Codespaces.

Thanks again for all of work on Candle!  I think it is the future of LLMOps and MLOps.

**Comment by noahgift** [comment]
Can verify VSCode + SSH to AWS works pretty well.  Note, I am working on getting permissions to P4 and will verify Falcon.

![Screenshot 2023-08-25 at 4 57 10 PM](https://github.com/huggingface/candle/assets/58792/2bc6e524-0b98-4952-9d53-bfc19aff818d)

**Comment by LaurentMazare** [comment]
Great, I think P4 being Pascal they may be a bit too old for bf16 but certainly worth trying.

**Comment by noahgift** [comment]
> Great, I think P4 being Pascal they may be a bit too old for bf16 but certainly worth trying.

Tell you what I will do a quick matrix test of all the new GPU instances on AWS will give me access to since I have a budget to test things out.  Related I may build a Rust spot instance launcher tool soon, and/or integrate EFS to store artifacts since I see myself doing a lot of work with Rust Candle.

**Comment by LaurentMazare** [comment]
Sounds great, looking forward to potential aws related tooling. I would recommend Ampere or Hopper if there is some availability for these, the upside is that you can use flash-attention on these (see the `flash-attn` feature) and this is quite a game changer for inference speed on transformer architectures (thanks to all the hard work that has been put in flash-attn-v2).

**Comment by noahgift** [comment]
Ok, I have some more info, and it does look like there may be a bug even with compute_cap >8.  I finally found a decent instance I could test with and selected with a G5:  https://aws.amazon.com/ec2/instance-types/g5/.

Instance type
g5.16xlarge

```
ubuntu@ip-172-31-21-63:~/candle$ git rev-parse HEAD
6559eae72cd55939f477f6d9ba45c228823c5b06
```

```
ubuntu@ip-172-31-21-63:~/candle$ nvidia-smi --query-gpu=compute_cap --format=csv
compute_cap
8.6
ubuntu@ip-172-31-21-63:~/candle$ RUST_BACKTRACE=1 cargo run --features cuda --example falcon --release -- --prompt "What is the best ty
> pe of Apple to eat"?
   Compiling candle-examples v0.1.3 (/home/ubuntu/candle/candle-examples)
    Finished release [optimized] target(s) in 11.55s
     Running `target/release/examples/falcon --prompt 'What is the best ty
pe of Apple to eat?'`
tokenizer.json [00:00:00] [████████████████████████████████████████████████████████████████████████] 2.61 MiB/2.61 MiB 26.94 MiB/s (0s)..del-00001-of-00002.safetensors [00:00:22] [█████████████████████████████████████████████████████] 9.27 GiB/9.27 GiB 419.26 MiB/s (0s)..del-00002-of-00002.safetensors [00:00:09] [█████████████████████████████████████████████████████] 4.18 GiB/4.18 GiB 458.51 MiB/s (0s)retrieved the files in 32.218427604s
loaded the model in 6.609368502s
starting the inference loop
Error: DriverError(CUDA_ERROR_NOT_FOUND, "named symbol not found") when loading is_u32_bf16

Stack backtrace:
   0: falcon::model::Falcon::forward
   1: falcon::TextGeneration::run
   2: falcon::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
   6: main
   7: __libc_start_main
   8: _start
```

**Comment by LaurentMazare** [comment]
That's pretty unexpected, it seems that the cuda kernel `is_u32_bf16` is not found. Maybe it's some caching issue somehow, could you try running `make clean-ptx` and giving it another go?
My guess is that you already built the example with a lower compute cap and the build system didn't have a way to detect that this has changed.

**Comment by noahgift** [comment]
> That's pretty unexpected, it seems that the cuda kernel `is_u32_bf16` is not found. Maybe it's some caching issue somehow, could you try running `make clean-ptx` and giving it another go? My guess is that you already built the example with a lower compute cap and the build system didn't have a way to detect that this has changed.

This was it!  Thanks again for all of the help, Candle is pretty cool!  I started with the p4, then switching the machine to a G5 which has a better cost profile, and better performance for developmant and is actually supported by Candle!  I simply "switched machine type", which I should have thought about, and could have created a subtle issue with the compilation.

Here is my workflow that verifies Falcon works a g5.16xlarge.  Later I will open another ticket on a related by different topic of machine compatibility for development, probably later this week and put some of my notes in there.

```
ubuntu@ip-172-31-21-63:~/candle$ nvidia-smi --query-gpu=compute_cap --format=csv
compute_cap
8.6
ubuntu@ip-172-31-21-63:~/candle$ make clean-ptx
find target -name "*.ptx" -type f -delete
echo "" > candle-kernels/src/lib.rs
touch candle-kernels/build.rs
touch candle-examples/build.rs
touch candle-flash-attn/build.rs
ubuntu@ip-172-31-21-63:~/candle$ RUST_BACKTRACE=1 cargo run --features cuda --example falcon --release -- --prompt "What is the best ty
> ^C
ubuntu@ip-172-31-21-63:~/candle$ RUST_BACKTRACE=1 cargo run --features cuda --example falcon --release -- --prompt "What is the best type of apple to eat?"
   Compiling candle-examples v0.1.3 (/home/ubuntu/candle/candle-examples)
   Compiling candle-kernels v0.1.3 (/home/ubuntu/candle/candle-kernels)
   Compiling candle-core v0.1.3 (/home/ubuntu/candle/candle-core)
   Compiling candle-nn v0.1.3 (/home/ubuntu/candle/candle-nn)
   Compiling candle-transformers v0.1.3 (/home/ubuntu/candle/candle-transformers)
   Compiling candle-datasets v0.1.3 (/home/ubuntu/candle/candle-datasets)
    Finished release [optimized] target(s) in 41.51s
     Running `target/release/examples/falcon --prompt 'What is the best type of apple to eat?'`
retrieved the files in 22.997771ms
loaded the model in 158.647230995s
starting the inference loop
> 9.624751977s
1 token: 193 '
'
> 102.677149ms
2 token: 487 'The'
> 43.732627ms
3 token: 935 ' best'
> 43.633475ms
4 token: 19088 ' apples'
> 43.604565ms
5 token: 271 ' to'
> 43.646475ms
6 token: 3781 ' eat'
> 68.119076ms
7 token: 362 ' are'
> 43.602295ms
8 token: 248 ' the'
> 43.662716ms
9 token: 3040 ' ones'
> 43.624095ms
10 token: 325 ' that'
> 43.707497ms
11 token: 362 ' are'
> 43.652905ms
12 token: 272 ' in'
> 43.697466ms
13 token: 2120 ' season'
> 43.602755ms
14 token: 25 '.'
> 43.654146ms
15 token: 193 '
'
> 43.645306ms
16 token: 487 'The'
> 43.607284ms
17 token: 935 ' best'
> 43.780128ms
18 token: 19088 ' apples'
> 43.699476ms
19 token: 271 ' to'
> 43.709886ms
20 token: 3781 ' eat'
> 43.732406ms
21 token: 362 ' are'
> 43.623285ms
22 token: 248 ' the'
> 43.687266ms
23 token: 3040 ' ones'
> 43.840629ms
24 token: 325 ' that'
> 43.825839ms
25 token: 362 ' are'
> 43.765788ms
26 token: 272 ' in'
> 43.789708ms
27 token: 2120 ' season'
> 43.863559ms
28 token: 25 '.'
> 43.84757ms
29 token: 193 '
'
> 43.846399ms
30 token: 487 'The'
> 43.835978ms
31 token: 935 ' best'
> 43.859219ms
32 token: 19088 ' apples'
> 43.809038ms
33 token: 271 ' to'
> 43.816158ms
34 token: 3781 ' eat'
> 43.836879ms
35 token: 362 ' are'
> 43.832719ms
36 token: 248 ' the'
> 43.844879ms
37 token: 3040 ' ones'
> 43.840609ms
38 token: 325 ' that'
> 49.265138ms
39 token: 362 ' are'
> 43.779528ms
40 token: 272 ' in'
> 43.782628ms
41 token: 2120 ' season'
> 43.810958ms
42 token: 25 '.'
> 43.782698ms
43 token: 193 '
'
> 43.879599ms
44 token: 487 'The'
> 43.834599ms
45 token: 935 ' best'
> 43.86694ms
46 token: 19088 ' apples'
> 43.8874ms
47 token: 271 ' to'
> 43.857309ms
48 token: 3781 ' eat'
> 43.945341ms
49 token: 362 ' are'
> 43.811019ms
50 token: 248 ' the'
> 43.87959ms
51 token: 3040 ' ones'
> 43.888ms
52 token: 325 ' that'
> 43.87292ms
53 token: 362 ' are'
> 43.822219ms
54 token: 272 ' in'
> 43.88727ms
55 token: 2120 ' season'
> 43.837039ms
56 token: 25 '.'
> 43.85941ms
57 token: 193 '
'
> 43.802489ms
58 token: 487 'The'
> 43.789688ms
59 token: 935 ' best'
> 43.792658ms
60 token: 19088 ' apples'
> 43.791908ms
61 token: 271 ' to'
> 43.791158ms
62 token: 3781 ' eat'
> 43.834899ms
63 token: 362 ' are'
> 43.752368ms
64 token: 248 ' the'
> 43.832158ms
65 token: 3040 ' ones'
> 43.793968ms
66 token: 325 ' that'
> 43.787038ms
67 token: 362 ' are'
> 43.735537ms
68 token: 272 ' in'
> 43.817829ms
69 token: 2120 ' season'
> 43.86399ms
70 token: 25 '.'
> 43.990323ms
71 token: 193 '
'
> 43.911951ms
72 token: 487 'The'
> 43.88645ms
73 token: 935 ' best'
> 43.863369ms
74 token: 19088 ' apples'
> 43.905461ms
75 token: 271 ' to'
> 43.87203ms
76 token: 3781 ' eat'
> 43.89619ms
77 token: 362 ' are'
> 43.890361ms
78 token: 248 ' the'
> 43.988762ms
79 token: 3040 ' ones'
> 43.909571ms
80 token: 325 ' that'
> 43.994063ms
81 token: 362 ' are'
> 43.932841ms
82 token: 272 ' in'
> 43.949341ms
83 token: 2120 ' season'
> 43.952721ms
84 token: 25 '.'
> 43.960452ms
85 token: 193 '
'
> 43.89845ms
86 token: 487 'The'
> 43.92011ms
87 token: 935 ' best'
> 43.870799ms
88 token: 19088 ' apples'
> 43.935321ms
89 token: 271 ' to'
> 43.933781ms
90 token: 3781 ' eat'
> 43.972932ms
91 token: 362 ' are'
> 43.953642ms
92 token: 248 ' the'
> 43.950331ms
93 token: 3040 ' ones'
> 43.785347ms
94 token: 325 ' that'
> 43.804188ms
95 token: 362 ' are'
> 43.770187ms
96 token: 272 ' in'
> 43.90394ms
97 token: 2120 ' season'
> 43.89419ms
98 token: 25 '.'
> 43.913241ms
99 token: 193 '
'
> 43.911771ms
100 token: 487 'The'
100 tokens generated (7.115549321467834 token/s)
----

The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The best apples to eat are the ones that are in season.
The
----
```
